apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: buildstrategies.build.dev
spec:
  group: build.dev
  names:
    kind: BuildStrategy
    listKind: BuildStrategyList
    plural: buildstrategies
    singular: buildstrategy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BuildStrategy is the Schema for the buildstrategies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BuildStrategySpec defines the desired state of BuildStrategy
          type: object
        status:
          description: BuildStrategyStatus defines the observed state of BuildStrategy
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
