name: Base images build

on:
  schedule:
  - cron: '0 3 * * *' # 3 AM UTC = before the nightly build
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    if: ${{ github.repository == 'shipwright-io/build' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - git
          - waiter
      max-parallel: 2

    steps:
      - uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io

      - name: Build Image
        working-directory: images/${{ matrix.image }}
        run: |
          NAMESPACE=$(tr '[:upper:]' '[:lower:]' <<<${{ github.repository_owner }})
          IMAGE=ghcr.io/${NAMESPACE}/base-${{ matrix.image }} docker buildx bake --push -f ../docker-bake.hcl
