name: Verify

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Tools
      run: |
        go install github.com/gordonklaus/ineffassign@latest
        go install golang.org/x/lint/golint@latest
        go install github.com/client9/misspell/cmd/misspell@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/maxbrunsfeld/counterfeiter/v6@latest

    - run: make govet
    - run: make ineffassign
    - run: make golint
    - run: make misspell
    - run: make staticcheck

    - name: Check make generate-crds
      run: |
        export GOPATH=$(go env GOPATH)
        make generate-crds
        if [[ $(git diff --stat) != '' ]]; then
          echo "CRD YAML is out of date, run make generate-crds"
          exit 1
        fi
